pipeline {
    stages {
		 stage('unit test') {
            steps {
                nodejs(nodeJSInstallationName: 'default') {
					sh 'npm install --only=dev'
					sh 'npm test '
				}
            }
        }
        stage('build') {
            steps {
                nodejs(nodeJSInstallationName: 'default') {
					sh 'npm install'
				}
            }
        }
    }
}
