pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                nodejs(nodeJSInstallationName: 'default') {
					sh 'npm install'
				}
            }
        }
    }
}
